pagination:
  per_page: 10
  size: 30
role:
  user: user
  manager: manager
each_index: 1
maximum:
  projects:
    name: 50
    abbreviation: 50
  workspace:
    name: 100
    description: 100
workspace_column: 2
workspace_row: 2
perpage_workspace: 10
pagination:
  user_per_page: 30
  user_size: 30
  project_per_page : 10
  per_page: 10
  size: 10
  manager: manager
each_user: 1
users_paginates: 30
default_password: "123456"
gender:
  female: female
  male: male
each_user: 1
